# Generated by Django 4.2.3 on 2023-07-18 18:35

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[clientes.models.validate_cpf]),
        ),
    ]
