# Generated by Django 4.2.3 on 2023-07-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_maxima', models.IntegerField()),
                ('vida', models.IntegerField()),
                ('ataque_maximo', models.IntegerField()),
                ('proximo_nivel', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_cura', models.FloatField()),
                ('fator_xp', models.FloatField()),
                ('fator_evolucao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Viloes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('vida_maxima', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('ataque_maximo', models.IntegerField()),
                ('imagem', models.TextField()),
            ],
        ),
    ]
