# Generated by Django 4.2.3 on 2023-07-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_autor_options'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='pedido',
        #     name='livros',
        #     field=models.ManyToManyField(through='pedidos.PedidoLivro', to='livros.livro'),
        # ),
        migrations.RemoveField(
            model_name='pedido',
            name='livros'
        ),
        migrations.AddField(
            model_name='pedido',
            name='livros',
            field=models.ManyToManyField(through='pedidos.PedidoLivro', to='livros.livro'),
        )
    ]
