# Generated by Django 4.2.3 on 2023-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_autor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
