# Generated by Django 4.2.4 on 2023-08-21 06:38

from django.db import migrations, models
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='assets/users_photos/default.png', max_length=500, null=True, upload_to='users_photos', validators=[user_data.models.validate_image_size]),
        ),
    ]
