# Generated by Django 4.2.4 on 2023-08-15 06:59

from django.db import migrations, models
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_customuser_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos', validators=[user_data.models.validate_image_size]),
        ),
    ]
