# Generated by Django 4.2.4 on 2023-08-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='points',
            field=models.IntegerField(),
        ),
    ]
