# Generated by Django 4.2.4 on 2023-08-09 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_data', '0003_alter_history_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_history', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
