# Generated by Django 4.2.4 on 2023-08-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_customuser_cnpj_alter_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
