# Generated by Django 4.2.4 on 2023-08-09 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_data', '0004_alter_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cep', models.CharField(max_length=8)),
                ('cpf', models.CharField(max_length=11)),
                ('addres_rua', models.CharField(max_length=255)),
                ('address_UF', models.CharField(max_length=2)),
                ('address_cidade', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.FileField(upload_to='')),
            ],
        ),
    ]
