# Generated by Django 4.2.4 on 2023-08-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos'),
        ),
    ]
