# Generated by Django 4.2.4 on 2023-08-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
