# Generated by Django 4.2.4 on 2023-08-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_customuser_email_contact_customuser_number_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
