# Generated by Django 4.2.4 on 2023-09-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_alter_customuser_number_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
