# Generated by Django 4.2.4 on 2023-09-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0010_customuser_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='addres_rua',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address_UF',
            new_name='address_state',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address_cidade',
            new_name='address_street',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='data_nascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='accepted_terms',
            new_name='is_terms_accepted',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_description',
            new_name='partner_company_description',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='partner_company_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name_slug',
            new_name='partner_company_name_slug',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_contact',
            new_name='partner_email_contact',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='number_contact',
            new_name='partner_number_contact',
        ),
    ]
