# Generated by Django 4.2.4 on 2023-09-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0012_rename_address_street_customuser_address_streets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_streets',
            new_name='address_street',
        ),
    ]
