# Generated by Django 4.2.4 on 2023-08-09 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizes',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_prizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
