# Generated by Django 4.2.4 on 2023-08-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prize', '0003_prizes_cost_in_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='prizes',
            name='used_by',
        ),
        migrations.AddField(
            model_name='prizes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='prize.prizecategory'),
        ),
        migrations.CreateModel(
            name='RedeemedPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_by', to='prize.prizes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_prizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'prize')},
            },
        ),
    ]
