# Generated by Django 4.2.4 on 2023-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0007_redeemedprizes_qr_code_alter_prizes_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizes',
            name='code',
        ),
        migrations.AddField(
            model_name='redeemedprizes',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='redeemedprizes',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
