# Generated by Django 4.2.4 on 2023-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0010_prizes_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
