# Generated by Django 4.2.4 on 2023-09-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0011_alter_prizes_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedprizes',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
