# Generated by Django 4.2.4 on 2023-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0012_redeemedprizes_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizes',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
