# Generated by Django 4.2.4 on 2023-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0014_remove_prizes_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
