# Generated by Django 4.2.4 on 2023-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0015_alter_prizes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizes',
            name='generated_by_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
