# Generated by Django 4.2.4 on 2023-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0016_prizes_generated_by_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='generated_by_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
