# Generated by Django 4.2.4 on 2023-09-09 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prize', '0017_alter_prizes_generated_by_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedeemedPrizes',
            new_name='UserRedeemedPrizes',
        ),
    ]
