# Generated by Django 4.2.4 on 2023-08-14 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('description', models.TextField()),
                ('location_link', models.URLField(default='', max_length=255)),
                ('coordinates_lat', models.CharField(default='', max_length=255)),
                ('coordinates_long', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TuristicPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('description', models.TextField()),
                ('numbers_qrcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code', models.CharField(max_length=255)),
                ('coordinates_lat', models.CharField(default='', max_length=255)),
                ('coordinates_long', models.CharField(default='', max_length=255)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_points', to='locations.location')),
            ],
        ),
    ]
