# Generated by Django 4.2.4 on 2023-08-20 21:35

from django.db import migrations, models
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations/Touristic_Points', validators=[user_data.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='location',
            name='locations_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations', validators=[user_data.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations', validators=[user_data.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations', validators=[user_data.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations', validators=[user_data.models.validate_image_size]),
        ),
    ]
