# Generated by Django 4.2.4 on 2023-08-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates_lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates_long',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='location_link',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='turisticpoint',
            name='coordinates_lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='turisticpoint',
            name='coordinates_long',
            field=models.CharField(default='', max_length=255),
        ),
    ]
