# Generated by Django 4.2.4 on 2023-08-09 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_coordinates_lat_location_coordinates_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
