# Generated by Django 4.2.4 on 2023-09-08 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_turisticpoint_photo_alter_location_locations_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('description', models.TextField()),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('coordinates_lat', models.CharField(default='', max_length=255)),
                ('coordinates_long', models.CharField(default='', max_length=255)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='Locations/Touristic_Points', validators=[user_data.models.validate_image_size])),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locations_photo',
            new_name='photo_4',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_link',
            new_name='review_link',
        ),
        migrations.DeleteModel(
            name='TuristicPoint',
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_points', to='locations.location'),
        ),
    ]
