# Generated by Django 4.2.4 on 2023-09-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_touristattraction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
